/* native_stubs.c -- generated by rustc_codegen_c
 * Portable C fallbacks for build-script-compiled native code. */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <string.h>
void abort(void);

/* ===== PSM fallbacks ===== */

__attribute__((weak)) void *rust_psm_stack_pointer(void) {
  void *sp;
#if defined(__aarch64__)
  __asm__ volatile("mov %0, sp" : "=r"(sp));
#elif defined(__x86_64__)
  __asm__ volatile("lea 8(%%rsp), %0" : "=r"(sp));
#elif defined(__i386__)
  __asm__ volatile("lea 4(%%esp), %0" : "=r"(sp));
#elif defined(__arm__)
  __asm__ volatile("mov %0, sp" : "=r"(sp));
#elif defined(__riscv)
  __asm__ volatile("mv %0, sp" : "=r"(sp));
#else
  volatile char anchor; sp = (void *)&anchor;
#endif
  return sp;
}

__attribute__((weak)) uint8_t rust_psm_stack_direction(void) {
  return 2; /* DESCENDING */
}

/* on_stack / replace_stack need precise stack control -> global asm. */

#if defined(__aarch64__)
/* ---- aarch64 (AAPCS64) ---- */
# ifdef __APPLE__
#  define PSM_FN(n)  ".globl _" n "\n.weak_definition _" n "\n_" n ":\n"
#  define PSM_END(n) ""
# else
#  define PSM_FN(n)  ".globl " n "\n.weak " n "\n.type " n ",%function\n" n ":\n"
#  define PSM_END(n) ".size " n ",.-" n "\n"
# endif
__asm__(
  PSM_FN("rust_psm_on_stack")
  "stp x29,x30,[sp,#-16]!\n"
  "mov x29,sp\n"
  "mov sp,x3\n"       /* x3 = new_sp */
  "blr x2\n"          /* x2 = callback(x0=data, x1=ret_ptr) */
  "mov sp,x29\n"
  "ldp x29,x30,[sp],#16\n"
  "ret\n"
  PSM_END("rust_psm_on_stack")
);
__asm__(
  PSM_FN("rust_psm_replace_stack")
  "mov sp,x2\n"       /* x2 = new_sp */
  "br  x1\n"          /* x1 = callback(x0=data), never returns */
  PSM_END("rust_psm_replace_stack")
);
# undef PSM_FN
# undef PSM_END

#elif defined(__x86_64__) && !defined(_WIN32)
/* ---- x86-64 System V ---- */
# ifdef __APPLE__
#  define PSM_FN(n)  ".globl _" n "\n.weak_definition _" n "\n_" n ":\n"
#  define PSM_END(n) ""
# else
#  define PSM_FN(n)  ".globl " n "\n.weak " n "\n.type " n ",@function\n" n ":\n"
#  define PSM_END(n) ".size " n ",.-" n "\n"
# endif
__asm__(
  PSM_FN("rust_psm_on_stack")
  "push %rbp\n"
  "mov  %rsp,%rbp\n"
  "mov  %rcx,%rsp\n"  /* rcx = new_sp */
  "call *%rdx\n"      /* rdx = callback(rdi=data, rsi=ret_ptr) */
  "mov  %rbp,%rsp\n"
  "pop  %rbp\n"
  "ret\n"
  PSM_END("rust_psm_on_stack")
);
__asm__(
  PSM_FN("rust_psm_replace_stack")
  "lea  -8(%rdx),%rsp\n"  /* rdx = new_sp */
  "jmp  *%rsi\n"           /* rsi = callback(rdi=data) */
  PSM_END("rust_psm_replace_stack")
);
# undef PSM_FN
# undef PSM_END

#elif defined(__i386__) && !defined(_WIN32)
/* ---- i386 fastcall ---- */
# define PSM_FN(n)  ".globl " n "\n.weak " n "\n.type " n ",@function\n" n ":\n"
# define PSM_END(n) ".size " n ",.-" n "\n"
__asm__(
  PSM_FN("rust_psm_on_stack")
  "push %ebp\n"
  "mov  %esp,%ebp\n"
  "mov  12(%ebp),%esp\n"  /* new_sp */
  "call *8(%ebp)\n"       /* callback(ecx=data, edx=ret_ptr) */
  "mov  %ebp,%esp\n"
  "pop  %ebp\n"
  "ret  $8\n"
  PSM_END("rust_psm_on_stack")
);
__asm__(
  PSM_FN("rust_psm_replace_stack")
  "mov  4(%esp),%esp\n"   /* new_sp */
  "call *%edx\n"          /* callback(ecx=data) */
  "ud2\n"
  PSM_END("rust_psm_replace_stack")
);
# undef PSM_FN
# undef PSM_END

#else
/* ---- Generic (no stack switching) ---- */
__attribute__((weak))
void rust_psm_on_stack(uintptr_t data, uintptr_t ret_ptr,
                        void (*cb)(uintptr_t, uintptr_t), void *sp) {
  (void)sp; cb(data, ret_ptr);
}
__attribute__((weak))
void rust_psm_replace_stack(uintptr_t data, void (*cb)(uintptr_t), void *sp) {
  (void)sp; cb(data); abort();
}
#endif /* PSM arch */

/* ===== BLAKE3 portable implementation ===== */

static inline uint32_t b3_rotr(uint32_t x, int n) {
  return (x >> n) | (x << (32 - n));
}
static const uint32_t B3_IV[8] = {
  0x6A09E667,0xBB67AE85,0x3C6EF372,0xA54FF53A,
  0x510E527F,0x9B05688C,0x1F83D9AB,0x5BE0CD19
};
static const uint8_t B3_SIGMA[7][16] = {
  { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15},
  { 2, 6, 3,10, 7, 0, 4,13, 1,11,12, 5, 9,14,15, 8},
  { 3, 4,10,12,13, 2, 7,14, 6, 5, 9, 0,11,15, 8, 1},
  {10, 7,12, 9,14, 3,13,15, 4, 0,11, 2, 5, 8, 1, 6},
  {12,13, 9,11,15,10,14, 8, 7, 2, 5, 3, 0, 1, 6, 4},
  { 9,14,11, 5, 8,12,15, 1,13, 3, 0,10, 2, 6, 4, 7},
  {11,15, 5, 0, 1, 9, 8, 6,14,10, 2,12, 3, 4, 7,13},
};

static void b3_g(uint32_t *s,int a,int b,int c,int d,uint32_t mx,uint32_t my){
  s[a]+=s[b]+mx; s[d]=b3_rotr(s[d]^s[a],16);
  s[c]+=s[d];    s[b]=b3_rotr(s[b]^s[c],12);
  s[a]+=s[b]+my; s[d]=b3_rotr(s[d]^s[a], 8);
  s[c]+=s[d];    s[b]=b3_rotr(s[b]^s[c], 7);
}

static void b3_compress(const uint32_t cv[8],const uint8_t blk[64],
                         uint8_t blen,uint64_t ctr,uint8_t fl,uint32_t out[16]){
  uint32_t m[16];
  for(int i=0;i<16;i++)
    m[i]=(uint32_t)blk[4*i]|((uint32_t)blk[4*i+1]<<8)
        |((uint32_t)blk[4*i+2]<<16)|((uint32_t)blk[4*i+3]<<24);
  uint32_t s[16]={
    cv[0],cv[1],cv[2],cv[3],cv[4],cv[5],cv[6],cv[7],
    B3_IV[0],B3_IV[1],B3_IV[2],B3_IV[3],
    (uint32_t)ctr,(uint32_t)(ctr>>32),(uint32_t)blen,(uint32_t)fl};
  for(int r=0;r<7;r++){
    const uint8_t*p=B3_SIGMA[r];
    b3_g(s,0,4, 8,12,m[p[ 0]],m[p[ 1]]); b3_g(s,1,5, 9,13,m[p[ 2]],m[p[ 3]]);
    b3_g(s,2,6,10,14,m[p[ 4]],m[p[ 5]]); b3_g(s,3,7,11,15,m[p[ 6]],m[p[ 7]]);
    b3_g(s,0,5,10,15,m[p[ 8]],m[p[ 9]]); b3_g(s,1,6,11,12,m[p[10]],m[p[11]]);
    b3_g(s,2,7, 8,13,m[p[12]],m[p[13]]); b3_g(s,3,4, 9,14,m[p[14]],m[p[15]]);
  }
  for(int i=0;i<8;i++){out[i]=s[i]^s[i+8]; out[i+8]=s[i+8]^cv[i];}
}

static void b3_hash_many(const uint8_t*const*inputs,size_t ni,size_t nblk,
                          const uint32_t key[8],uint64_t ctr,bool inc,
                          uint8_t fl,uint8_t fs,uint8_t fe,uint8_t*out){
  for(size_t i=0;i<ni;i++){
    uint32_t cv[8]; memcpy(cv,key,32);
    uint64_t c=inc?ctr+i:ctr;
    const uint8_t*inp=inputs[i];
    for(size_t b=0;b<nblk;b++){
      uint8_t bf=fl|(b==0?fs:0)|(b+1==nblk?fe:0);
      uint32_t f[16]; b3_compress(cv,inp+b*64,64,c,bf,f); memcpy(cv,f,32);
    }
    memcpy(out+i*32,cv,32);
  }
}

static void b3_compress_ip(uint32_t cv[8],const uint8_t blk[64],
                            uint8_t blen,uint64_t ctr,uint8_t fl){
  uint32_t o[16]; b3_compress(cv,blk,blen,ctr,fl,o); memcpy(cv,o,32);
}

static void b3_compress_xof(const uint32_t cv[8],const uint8_t blk[64],
                              uint8_t blen,uint64_t ctr,uint8_t fl,uint8_t out[64]){
  uint32_t st[16]; b3_compress(cv,blk,blen,ctr,fl,st);
  for(int i=0;i<16;i++){
    out[4*i]=(uint8_t)st[i]; out[4*i+1]=(uint8_t)(st[i]>>8);
    out[4*i+2]=(uint8_t)(st[i]>>16); out[4*i+3]=(uint8_t)(st[i]>>24);
  }
}

/* ===== BLAKE3 weak wrappers ===== */

#define B3_HASH_MANY(name) \
  __attribute__((weak)) void name( \
      const uint8_t*const*inputs,size_t ni,size_t nblk, \
      const uint32_t key[8],uint64_t ctr,bool inc, \
      uint8_t fl,uint8_t fs,uint8_t fe,uint8_t*out){ \
    b3_hash_many(inputs,ni,nblk,key,ctr,inc,fl,fs,fe,out);}

#define B3_COMPRESS_IP(name) \
  __attribute__((weak)) void name( \
      uint32_t cv[8],const uint8_t blk[64], \
      uint8_t blen,uint64_t ctr,uint8_t fl){ \
    b3_compress_ip(cv,blk,blen,ctr,fl);}

#define B3_COMPRESS_XOF(name) \
  __attribute__((weak)) void name( \
      const uint32_t cv[8],const uint8_t blk[64], \
      uint8_t blen,uint64_t ctr,uint8_t fl,uint8_t out[64]){ \
    b3_compress_xof(cv,blk,blen,ctr,fl,out);}

/* NEON (aarch64 only) */
#if defined(__aarch64__)
B3_HASH_MANY(blake3_hash_many_neon)
#endif

/* SSE2 / SSE4.1 / AVX2 / AVX-512 (x86/x86_64 only) */
#if defined(__x86_64__) || defined(__i386__)
B3_HASH_MANY(blake3_hash_many_sse2)
B3_COMPRESS_IP(blake3_compress_in_place_sse2)
B3_COMPRESS_XOF(blake3_compress_xof_sse2)
B3_HASH_MANY(blake3_hash_many_sse41)
B3_COMPRESS_IP(blake3_compress_in_place_sse41)
B3_COMPRESS_XOF(blake3_compress_xof_sse41)
B3_HASH_MANY(blake3_hash_many_avx2)
B3_HASH_MANY(blake3_hash_many_avx512)
B3_COMPRESS_IP(blake3_compress_in_place_avx512)
B3_COMPRESS_XOF(blake3_compress_xof_avx512)
#endif

#undef B3_HASH_MANY
#undef B3_COMPRESS_IP
#undef B3_COMPRESS_XOF
