/* Generated by rustc_codegen_c */
#ifndef __RUSTC_CODEGEN_C_PREAMBLE
#define __RUSTC_CODEGEN_C_PREAMBLE
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <math.h>
#include <stdarg.h>
#include <stdatomic.h>
void *memcpy(void *, const void *, size_t);
void *memset(void *, int, size_t);
void *memmove(void *, const void *, size_t);
int memcmp(const void *, const void *, size_t);
void abort(void);
#include <setjmp.h>
#define __rustc_setjmp setjmp
#define __rustc_longjmp longjmp
struct __rustc_unwind_context {
  jmp_buf buf;
  void *exception_ptr;
  struct __rustc_unwind_context *prev;
};
#pragma weak __rustc_unwind_chain
_Thread_local struct __rustc_unwind_context *__rustc_unwind_chain;
#pragma weak _Unwind_RaiseException
int _Unwind_RaiseException(void *exception_object) {
  if (__rustc_unwind_chain) {
    __rustc_unwind_chain->exception_ptr = exception_object;
    __rustc_longjmp(__rustc_unwind_chain->buf, 1);
  }
  abort();
  return 3;
}
#pragma weak __rust_try
int __rust_try(void (*try_fn)(void *), void *data, void (*catch_fn)(void *, void *)) {
  struct __rustc_unwind_context __ctx;
  __ctx.prev = __rustc_unwind_chain;
  __ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__ctx;
  if (__rustc_setjmp(__ctx.buf) == 0) {
    try_fn(data);
    __rustc_unwind_chain = __ctx.prev;
    return 0;
  } else {
    void *__exn = __ctx.exception_ptr;
    __rustc_unwind_chain = __ctx.prev;
    catch_fn(data, __exn);
    return 1;
  }
}

#ifdef __SIZEOF_INT128__
typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;
#else
#error "128-bit integer support requires __int128 (GCC/Clang)"
#endif

#ifndef __FLT16_MAX__
#ifdef __clang__
#if __is_identifier(_Float16)
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#else
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#endif
#ifndef __FLT128_MAX__
#ifdef __clang__
#if __is_identifier(_Float128)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#else
/* GCC: _Float128 is a builtin on x86_64; on other arches, fall back */
#ifndef __SIZEOF_FLOAT128__
#if !defined(__x86_64__) && !defined(__i386__)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#endif
#endif
#endif

/* ---- Portable bit-manipulation helpers ---- */

static inline int __rustc_clz32(uint32_t x) {
  int n = 0;
  if ((x & 0xFFFF0000u) == 0) { n += 16; x <<= 16; }
  if ((x & 0xFF000000u) == 0) { n += 8;  x <<= 8; }
  if ((x & 0xF0000000u) == 0) { n += 4;  x <<= 4; }
  if ((x & 0xC0000000u) == 0) { n += 2;  x <<= 2; }
  if ((x & 0x80000000u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_clz64(uint64_t x) {
  uint32_t hi = (uint32_t)(x >> 32);
  if (hi != 0) return __rustc_clz32(hi);
  return 32 + __rustc_clz32((uint32_t)x);
}

static inline int __rustc_ctz32(uint32_t x) {
  int n = 0;
  if ((x & 0x0000FFFFu) == 0) { n += 16; x >>= 16; }
  if ((x & 0x000000FFu) == 0) { n += 8;  x >>= 8; }
  if ((x & 0x0000000Fu) == 0) { n += 4;  x >>= 4; }
  if ((x & 0x00000003u) == 0) { n += 2;  x >>= 2; }
  if ((x & 0x00000001u) == 0) { n += 1; }
  return n;
}

static inline int __rustc_ctz64(uint64_t x) {
  uint32_t lo = (uint32_t)x;
  if (lo != 0) return __rustc_ctz32(lo);
  return 32 + __rustc_ctz32((uint32_t)(x >> 32));
}

static inline int __rustc_popcount32(uint32_t x) {
  x = x - ((x >> 1) & 0x55555555u);
  x = (x & 0x33333333u) + ((x >> 2) & 0x33333333u);
  x = (x + (x >> 4)) & 0x0F0F0F0Fu;
  return (int)((x * 0x01010101u) >> 24);
}

static inline int __rustc_popcount64(uint64_t x) {
  x = x - ((x >> 1) & 0x5555555555555555ULL);
  x = (x & 0x3333333333333333ULL) + ((x >> 2) & 0x3333333333333333ULL);
  x = (x + (x >> 4)) & 0x0F0F0F0F0F0F0F0FULL;
  return (int)((x * 0x0101010101010101ULL) >> 56);
}

static inline uint16_t __rustc_bswap16(uint16_t x) {
  return (uint16_t)((x >> 8) | (x << 8));
}

static inline uint32_t __rustc_bswap32(uint32_t x) {
  x = ((x & 0xFF00FF00u) >> 8) | ((x & 0x00FF00FFu) << 8);
  return (x >> 16) | (x << 16);
}

static inline uint64_t __rustc_bswap64(uint64_t x) {
  x = ((x & 0xFF00FF00FF00FF00ULL) >> 8) | ((x & 0x00FF00FF00FF00FFULL) << 8);
  x = ((x & 0xFFFF0000FFFF0000ULL) >> 16) | ((x & 0x0000FFFF0000FFFFULL) << 16);
  return (x >> 32) | (x << 32);
}

/* ---- Portable overflow detection (widening approach) ---- */

#define RUSTC_DEFINE_OVERFLOW_WIDEN(suffix, type, wide_type) \
  static inline _Bool __rustc_add_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a + (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_sub_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a - (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  } \
  static inline _Bool __rustc_mul_overflow_##suffix(type a, type b, type *r) { \
    wide_type w = (wide_type)a * (wide_type)b; \
    *r = (type)w; \
    return w != (wide_type)*r; \
  }

RUSTC_DEFINE_OVERFLOW_WIDEN(i8, int8_t, int16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u8, uint8_t, uint16_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i16, int16_t, int32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u16, uint16_t, uint32_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i32, int32_t, int64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u32, uint32_t, uint64_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(i64, int64_t, int128_t)
RUSTC_DEFINE_OVERFLOW_WIDEN(u64, uint64_t, uint128_t)

/* 128-bit overflow: cannot widen, use bitwise checks */
static inline _Bool __rustc_add_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a + b; return *r < a;
}
static inline _Bool __rustc_sub_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a - b; return a < b;
}
static inline _Bool __rustc_mul_overflow_u128(uint128_t a, uint128_t b, uint128_t *r) {
  *r = a * b; return (a != 0 && *r / a != b);
}
static inline _Bool __rustc_add_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua + ub);
  return (int128_t)((~(ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_sub_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  uint128_t ua = (uint128_t)a, ub = (uint128_t)b;
  *r = (int128_t)(ua - ub);
  return (int128_t)(((ua ^ ub)) & ((uint128_t)*r ^ ua)) < 0;
}
static inline _Bool __rustc_mul_overflow_i128(int128_t a, int128_t b, int128_t *r) {
  *r = a * b;
  if (a == 0) return 0;
  return *r / a != b;
}

/* Pointer-width integer typedefs matching fixed-width types.
   This avoids incompatible-pointer-types errors on targets where
   uintptr_t is a different typedef than uint{32,64}_t (e.g. emscripten
   where uintptr_t is 'unsigned long' but uint32_t is 'unsigned int'). */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
typedef uint64_t __rustc_usize;
typedef int64_t  __rustc_isize;
#else
typedef uint32_t __rustc_usize;
typedef int32_t  __rustc_isize;
#endif

/* Pointer-width overflow aliases */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFULL
#define __rustc_add_overflow_usize __rustc_add_overflow_u64
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u64
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u64
#define __rustc_add_overflow_isize __rustc_add_overflow_i64
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i64
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i64
#else
#define __rustc_add_overflow_usize __rustc_add_overflow_u32
#define __rustc_sub_overflow_usize __rustc_sub_overflow_u32
#define __rustc_mul_overflow_usize __rustc_mul_overflow_u32
#define __rustc_add_overflow_isize __rustc_add_overflow_i32
#define __rustc_sub_overflow_isize __rustc_sub_overflow_i32
#define __rustc_mul_overflow_isize __rustc_mul_overflow_i32
#endif

#undef RUSTC_DEFINE_OVERFLOW_WIDEN

#endif /* __RUSTC_CODEGEN_C_PREAMBLE */

