/* Generated by rustc_codegen_c */
#ifndef __RUSTC_CODEGEN_C_PREAMBLE
#define __RUSTC_CODEGEN_C_PREAMBLE
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <math.h>
#include <stdarg.h>
#include <stdatomic.h>
void *memcpy(void *, const void *, size_t);
void *memset(void *, int, size_t);
void *memmove(void *, const void *, size_t);
int memcmp(const void *, const void *, size_t);
void abort(void);
#include <setjmp.h>
#define __rustc_setjmp setjmp
#define __rustc_longjmp longjmp
struct __rustc_unwind_context {
  jmp_buf buf;
  void *exception_ptr;
  struct __rustc_unwind_context *prev;
};
__attribute__((weak, visibility("default"))) __thread struct __rustc_unwind_context *__rustc_unwind_chain;
__attribute__((weak)) int __rust_try(void (*try_fn)(void *), void *data, void (*catch_fn)(void *, void *)) {
  struct __rustc_unwind_context __ctx;
  __ctx.prev = __rustc_unwind_chain;
  __ctx.exception_ptr = (void *)0;
  __rustc_unwind_chain = &__ctx;
  if (__rustc_setjmp(__ctx.buf) == 0) {
    try_fn(data);
    __rustc_unwind_chain = __ctx.prev;
    return 0;
  } else {
    void *__exn = __ctx.exception_ptr;
    __rustc_unwind_chain = __ctx.prev;
    catch_fn(data, __exn);
    return 1;
  }
}

#ifdef __SIZEOF_INT128__
typedef __int128 int128_t;
typedef unsigned __int128 uint128_t;
#else
#error "128-bit integer support requires __int128 (GCC/Clang)"
#endif

#ifndef __FLT16_MAX__
#ifdef __clang__
#if __is_identifier(_Float16)
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#else
typedef unsigned short _Float16; /* fallback: no hardware f16 */
#endif
#endif
#ifndef __FLT128_MAX__
#ifdef __clang__
#if __is_identifier(_Float128)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#else
/* GCC: _Float128 is a builtin on x86_64; on other arches, fall back */
#ifndef __SIZEOF_FLOAT128__
#if !defined(__x86_64__) && !defined(__i386__)
typedef long double _Float128; /* fallback: reduced precision */
#endif
#endif
#endif
#endif

#ifdef _MSC_VER
#include <intrin.h>
#define __builtin_unreachable() __assume(0)
#define __builtin_expect(expr, val) (expr)
#define __builtin_isnan(x) _isnan(x)
#endif

#endif /* __RUSTC_CODEGEN_C_PREAMBLE */

