name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - LICENSE-*
  pull_request:
    branches: [main]
    paths-ignore:
      - README.md
      - LICENSE-*
  workflow_call:
  workflow_dispatch:

env:
  RUST_BRANCH: rustic-1.94.1
  MAX_FAIL_PERCENT: 1
  BOOTSTRAP_TOML: |
    profile = "dist"

    [llvm]
    download-ci-llvm = true

    [rust]
    codegen-backends = ["c"]

jobs:
  build-test:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
        cc: [gcc, clang]
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout rust
        uses: actions/checkout@v6
        with:
          repository: rustic-compiler/rust
          ref: ${{ env.RUST_BRANCH }}
          fetch-depth: 0
          path: rust

      - name: Checkout rustc_codegen_c
        uses: actions/checkout@v6
        with:
          path: rustc_codegen_c

      - name: Create symlink
        run: cd rust/compiler && ln -s ../../rustc_codegen_c rustc_codegen_c

      - name: Configure
        run: |
          echo "$BOOTSTRAP_TOML" > rust/bootstrap.toml
          echo "CC=${{ matrix.cc }}" >> "$GITHUB_ENV"
          echo "HOST_TUPLE=$(rustc --print=host-tuple)" >> "$GITHUB_ENV"

      - name: Test
        run: cd rust && ./compiler/rustc_codegen_c/test.sh

      - name: Build
        run: cd rust && ./x build compiler library

      - name: Create stage2 tarball
        run: |
          cd rust/build/host/stage2
          tar czf "$GITHUB_WORKSPACE/rustic-toolchain-$HOST_TUPLE-${{ matrix.cc }}.tar.gz" .
      - name: Create csources tarball
        run: |
          mkdir csources
          cp rust/build/$HOST_TUPLE/stage2-rustc/$HOST_TUPLE/release/Makefile ./
          cp rust/build/$HOST_TUPLE/stage2-rustc/$HOST_TUPLE/release/csources/*.c ./csources/
          cp rust/build/$HOST_TUPLE/stage1-std/$HOST_TUPLE/release/csources/*.c ./csources/
          tar czf "$GITHUB_WORKSPACE/rustic-rustc-csources-$HOST_TUPLE-${{ matrix.cc }}.tar.gz" csources Makefile


      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: rustic-${{ env.HOST_TUPLE }}-${{ matrix.cc }}
          path: |
            rustic-toolchain-${{ env.HOST_TUPLE }}-${{ matrix.cc }}.tar.gz
            rustic-rustc-csources-${{ env.HOST_TUPLE }}-${{ matrix.cc }}.tar.gz
