name: Release

on:
  push:
    tags:
      - 'release-*'

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  release:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          files: '*.tar.gz'
          draft: true
          generate_release_notes: true
